### ISSUE TITLE
Tiffany Imperiale -  Malware Analysis 

### ISSUE THREAD

**Issue by cameronkc** [cameronkc/DF-GROUP2-REPO#1]
Malware Analysis Demonstration

**Comment by tiffany-imperiale** [comment]
![malfind](https://user-images.githubusercontent.com/77411087/136070757-037eab92-4365-45c5-a951-a9a8305a7789.png)
)

**Comment by tiffany-imperiale** [comment]
![volatilitymalware](https://user-images.githubusercontent.com/77411087/136071075-3686ef66-84e7-4bef-80d0-e7bb3a1aafa7.jpg)
